services:
  candy:
    build: ./
    environment:
      - CUDACXX=/usr/local/cuda/bin/nvcc
    volumes:
      - "..:/workspace"
    working_dir: /workspace
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
